[workspace]
members = [
    "crates/provenance_ssg",
    "crates/manifest_contract",
    "crates/renderers",
    "crates/badges",
    "crates/tools",
    "xtask"
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
