name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            crates/proofdown_parser/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Outer + nested checks (fmt, clippy, check)
        run: cargo xtask check-all

      - name: Outer + nested tests
        run: cargo xtask test-all

      - name: Cargo dependency duplicates
        run: cargo tree -d

      - name: Feature-gated integration build
        run: cargo xtask ci-integration-build

  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable corepack & activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.12.2 --activate

      - name: Build example site
        working-directory: e2e
        run: |
          pnpm install
          pnpm run build:site

      - name: Run Cypress tests
        working-directory: e2e
        run: pnpm run test
